before:
  hooks:
builds:
  - id: "linux"
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
      - mipsle
    goos:
      - linux
    goarm:
      - 6
      - 7
    gomips:
      - softfloat
  - id: "non-linux"
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - example.yaml
      - systemd/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: dschanoeh
    name: hover-ddns
